using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ValuationServiceAPI.Models;

public class ConditionReportDocument : IDocument
{
    private readonly ConditionReport _report;

    public ConditionReportDocument(ConditionReport report)
    {
        _report = report;
    }

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Margin(40);
            page.Header().Text($"Condition Report").FontSize(20).Bold().AlignCenter();
            page.Content().PaddingVertical(10).Column(col =>
            {
                col.Item().Text($"Title: {_report.Title}");
                col.Item().Text($"Summary: {_report.Summary}");
                col.Item().Text($"Material: {_report.MaterialCondition}");
                col.Item().Text($"Functionality: {_report.Functionality}");
                col.Item().Text($"Remarks: {_report.ComponentRemarks}");
                col.Item().Text($"Authenticity: {_report.AuthenticityDetails}");
                col.Item().Text($"Dimensions: {_report.Dimensions}");
                col.Item().Text($"Assessed By: {_report.AssessedBy}");
                col.Item().Text($"Report Date: {_report.ReportDate:yyyy-MM-dd}");
            });
            page.Footer().AlignCenter().Text("Generated by ValuationService");
        });
    }
}
